openapi: 3.0.0
info:
  title: Simple Test API
  version: 1.0.0
paths:
  /users:
    post:
      operationId: createUser
      summary: Create a new user
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
  /users/{userId}:
    get:
      operationId: getUserById
      summary: Get a user by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A user object